version: '3.8'

services:
  app:
    image: min3187/myapp:latest
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}  # RDS 사용자 이름
      DB_PASSWORD: ${DB_PASSWORD} # RDS 비밀번호
      REDIS_HOST: redis  # 도커 내에서 Redis 사용
      REDIS_PORT: 6379  # Redis 포트
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_REGION: ${S3_REGION}
      CLOUD_FRONT_PATH: ${CLOUD_FRONT_PATH}

    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge