version: '3.8'

services:
  app:

    image: min3187/challenge-final
    container_name: challenge-app
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}  # RDS 사용자 이름
      DB_PASSWORD: ${DB_PASSWORD} # RDS 비밀번호
      REDIS_HOST: redis  # 도커 내에서 Redis 사용
      REDIS_PORT: 6379  # Redis 포트
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

      # ✅ OAuth 키들
      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      GOOGLE_REDIRECT_URI: http://your-domain.com/login/oauth2/code/google

      KAKAO_CLIENT_ID: your-kakao-client-id
      KAKAO_CLIENT_SECRET: your-kakao-client-secret
      KAKAO_REDIRECT_URI: http://your-domain.com/login/oauth2/code/kakao

      NAVER_CLIENT_ID: your-naver-client-id
      NAVER_CLIENT_SECRET: your-naver-client-secret
      NAVER_REDIRECT_URI: http://your-domain.com/login/oauth2/code/naver
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge