version: '3.8'

services:
  app:
    build: .
    container_name: challenge-app
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}  # RDS 사용자 이름
      DB_PASSWORD: ${DB_PASSWORD} # RDS 비밀번호
      REDIS_HOST: redis  # 도커 내에서 Redis 사용
      REDIS_PORT: 6379  # Redis 포트
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge